apiVersion: v1
kind: Service
metadata:
  name: test-app
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    name: test-app
    app: frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
spec:
  rules:
  - http:
     paths:
     - path: /
       pathType: ImplementationSpecific
       backend:
         service:
           name: test-app
           port:
             name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  selector:
    matchLabels:
      name: test-app
      app: frontend
  template:
    metadata:
      labels:
        name: test-app
        app: frontend
    spec:
      containers:
      - name: phpmyadmin
        image: austinobioma/demo_app:latest
        env:
        - name: PMA_ARBITRARY
          value: "1"
        ports:
        - name: http
          containerPort: 80
---
